language: dart
sudo: false
dart:
  - dev
  - stable
  - 1.22.1
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test
matrix:
  include:
    - dart: dev
      dart_task: dartfmt
    # Only care about being analyzer clean for dev and stable
    - dart: dev
      dart_task: dartanalyzer
    - dart: stable
      dart_task: dartanalyzer
