language: dart
branches:
  only: [master]
dart:
  - dev
  - 2.6.0
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test --test-randomize-ordering-seed=random
  - test -p chrome --test-randomize-ordering-seed=random

matrix:
  include:
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task:
        dartanalyzer: --fatal-warnings --fatal-infos .
    - dart: 2.6.0
      dart_task:
        dartanalyzer: --fatal-warnings .
