language: dart
branches:
  only: [master]
dart:
  # Skipping dev until Dart 2.1.0-dev is out
  #- dev
  - stable
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test
  - test -p chrome
  - dartfmt
  - dartanalyzer
