analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    dead_code: error
    override_on_non_overriding_method: error
    unused_element: error
    unused_import: error
    unused_local_variable: error
linter:
  rules:
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_types
    - comment_references
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - no_duplicate_case_values
    - non_constant_identifier_names
    - omit_local_variable_types
    - only_throw_errors
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_is_not_empty
    - prefer_single_quotes
    - recursive_getters
    - slash_for_doc_comments
    - test_types_in_equals
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
