name: stream_transform
description: A collection of utilities to transform and manipulate streams.
author: Dart Team <misc@dartlang.org>
homepage: https://www.github.com/dart-lang/stream_transform
version: 0.0.20

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.5.0
  test: ^1.0.0
  # Example
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
