name: stream_transform
version: 2.1.1-wip
description: A collection of utilities to transform and manipulate streams.
repository: https://github.com/dart-lang/stream_transform

environment:
  sdk: ^3.1.0

dev_dependencies:
  async: ^2.5.0
  dart_flutter_team_lints: ^2.0.0
  fake_async: ^1.3.0
  test: ^1.16.0
