name: stream_transform
description: A collection of utilities to transform and manipulate streams.
author: Dart Team <misc@dartlang.org>
homepage: https://www.github.com/dart-lang/stream_transform
version: 0.0.19

environment:
  sdk: ">=2.2.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.5.0
  test: ^1.0.0
