name: stream_transform
description: A collection of utilities to transform and manipulate streams.
homepage: https://github.com/dart-lang/stream_transform
version: 2.0.0-nullsafety.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  async: ^2.5.0-nullsafety
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
